project:
  type: website
  output-dir: docs

website:
  title: "Relatórios IC"
  navbar:
    background: primary
    search: true
    left:
      - text: "Sobre"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/cheriroga/relatorios
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

