project:
  type: website

website:
  title: "Relatórios IC"
  navbar:
    background: primary
    search: true
    left:
      - text: "Sobre"
        href: about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

