---
title: "Relátorio de Modelos Poluentes"
format: html
toc: true
---

## Bibliotecas

```{r, results='hide', message=F, warning=F}
require(glarma)
require(performance)
require(kableExtra)
require(tidyverse)
```

## Base de Dados

```{r}
df <- read.delim("Data_CPDO.txt")
```

## Matrix of Correlation

```{r}
require(Hmisc)
```

```{r}
a <- df[, 1:9]

matrix <-  rcorr(as.matrix(a))

cor_matrix <- matrix$r

p_value_matrix <- matrix$P

cor_matrix[lower.tri(cor_matrix, diag = TRUE)] <- ""
p_value_matrix[lower.tri(p_value_matrix, diag = TRUE)] <- ""
```

```{r}
cor_matrix %>% 
  kable("html", align = "c") %>% 
  kable_styling()
```

```{r}
p_value_matrix %>%
  kable("html", align = "c") %>% 
  kable_styling()
```

## NO

```{r}
y <- df[,1]
X1 <- as.matrix(df[,4])

Trend <- 1:84
Intercepto <- rep(1,84)
X1 <- cbind(Intercepto, Trend, X1, df$cos6, df$cos12, df$sen6, df$sen12)
colnames(X1) <- c("Intercepto", "Trend", "NO", "cos6", "cos12", "sen6", "sen12")
```

### GLARMA Poisson

```{r}
glarma_poi <- glarma(y, X1, thetaLags = NULL, phiLags = 1, type = "Poi",
                     method = "FS", residuals= "Pearson",
                     maxit = 100, grad = 1e-6)

```

```{r}
summary(glarma_poi)
```

```{r}
glarma_poi
```

```{r}
par(mfrow = c(2, 1))
acf(glarma_poi$residuals)
pacf(glarma_poi$residuals)
```

```{r}
par(mfrow=c(2,3))
plot(glarma_poi)
```

### GLARMA Binomial Negativo

```{r}
glarma_nb <- glarma(y, X1, thetaLags = NULL, phiLags = 1, type = "NegBin",
                    method = "FS", residuals= "Pearson",
                    maxit = 100, grad = 1e-6)
```

```{r}
summary(glarma_nb)
```

```{r}
glarma_nb
```

```{r}
par(mfrow = c(2, 1))
acf(glarma_nb$residuals)
pacf(glarma_nb$residuals)
```

```{r}
par(mfrow=c(2,3))
plot(glarma_nb)
```

## NOX

```{r}
y <- df[,1]
X2 <- as.matrix(df[,6])

Trend <- 1:84
Intercepto <- rep(1,84)
X2 <- cbind(Intercepto, Trend, X2, df$cos6, df$cos12, df$sen6, df$sen12)
colnames(X2) <- c("Intercepto", "Trend", "NOX", "cos6", "cos12", "sen6", "sen12")
```

### GLARMA Binomial Negativo

```{r}
glarma_nb <- glarma(y, X2, thetaLags = NULL, phiLags = 1, type = "NegBin",
                    method = "FS", residuals= "Pearson",
                    maxit = 100, grad = 1e-6)
```

```{r}
summary(glarma_nb)
```

```{r}
glarma_nb
```

```{r}
par(mfrow = c(2, 1))
acf(glarma_nb$residuals)
pacf(glarma_nb$residuals)
```

```{r}
par(mfrow=c(2,3))
plot(glarma_nb)
```

## NO e NOX

```{r}
y <- df[,1]
X1 <- as.matrix(df[,4])
X2 <- as.matrix(df[,6])

Trend <- 1:84
Intercepto <- rep(1,84)
X3 <- cbind(Intercepto, Trend, X1, X2, df$cos6, df$cos12, df$sen6, df$sen12)
colnames(X3) <- c("Intercepto", "Trend", "NO", "NOX", "cos6", "cos12", "sen6", "sen12")
```

### GLARMA Binomial Negativo

```{r}
glarma_nb <- glarma(y, X3, thetaLags = NULL, phiLags = c(1,6) , type = "NegBin",
                    method = "FS", residuals= "Pearson",
                    maxit = 100, grad = 1e-6)
```

```{r}
summary(glarma_nb)
```

```{r}
glarma_nb
```

```{r}
par(mfrow = c(2, 1))
acf(glarma_nb$residuals)
pacf(glarma_nb$residuals)
```

```{r}
par(mfrow=c(2,3))
plot(glarma_nb)
```
