---
title: "relatorio3"
toc: true
code-fold: true
---

### Bibliotecas

```{r, results='hide', message=F, warning=F}
library(corrr)
library(ggcorrplot)
library(FactoMineR)
library(factoextra)
library(glarma)
```

## Explorando dos dados

### Dados dos poluentes

```{r}
df <- read.delim("Data_CPDO.txt")
poluentes <- df[, 2:9]
```

### Calcular a matriz de correlação

```{r}
corr_matrix <- cor(as.matrix(poluentes))
ggcorrplot(corr_matrix)
```

## Aplicação de PCA

```{r}
data.pca <- princomp(corr_matrix)
summary(data.pca)
```

## Visualização dos componentes principais

### Gráfico Scree

```{r}
fviz_eig(data.pca, addlabels = TRUE)
```

### Biplot dos atributos

```{r}
fviz_pca_var(data.pca, col.var = "black")
```

### Contribuição de cada variável

```{r}
fviz_cos2(data.pca, choice = "var", axes = 1:2)
```

### Biplot combinado com cos2

```{r}
fviz_pca_var(data.pca, col.var = "cos2",
            gradient.cols = c("black", "orange", "green"),
            repel = TRUE)
```

# Resultado PCA

```{r}
pca_result <- prcomp(poluentes, center = TRUE, scale. = TRUE)

# Selecionar os primeiros componentes principais (com base em variância explicada, por exemplo)
variancia_explicada <- summary(pca_result)$importance[2, ]  # Proporção da variância explicada
num_componentes <- which(cumsum(variancia_explicada) >= 0.8)[1]  # 80% da variância explicada
pca_vars <- pca_result$x[, 1:num_componentes]  # Seleciona os componentes principais

Trend <- 1:84

df_complicado <- as.matrix(cbind(pca_vars, df[,8:13], Trend))

y <- df[, 1]

pca_vars

```


```{r}
corr_matrix <- cor(df_complicado)
ggcorrplot(corr_matrix)
```


## GLARMA

### Poi

```{r}
glarma_poi <- glarma(y, df_complicado, thetaLags = NULL, phiLags = 1, type = "Poi",
                    method = "FS", residuals= "Pearson",
                    maxit = 100, grad = 1e-6)

summary(glarma_poi)

```

```{r}
par(mfrow = c(2, 1))
acf(glarma_poi$residuals)
pacf(glarma_poi$residuals)
```

```{r}
par(mfrow=c(2,3))
plot(glarma_poi)
```

### NegBin

```{r}

glarma_nb <- glarma(y, df_complicado, thetaLags = 1, phiLags = NULL, type = "NegBin",
                    method = "FS", residuals= "Pearson",
                    maxit = 100, grad = 1e-6)

summary(glarma_nb)
```

```{r}
par(mfrow = c(2, 1))
acf(glarma_nb$residuals)
pacf(glarma_nb$residuals)
```

```{r}
par(mfrow=c(2,3))
plot(glarma_nb)
```