<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Relátorio - Indicadores Ambientais e Bronquite Aguda – Relatórios IC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Relatórios IC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Sobre</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/cheriroga/relatorios"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pré-requisitos" id="toc-pré-requisitos" class="nav-link active" data-scroll-target="#pré-requisitos">Pré-requisitos</a>
  <ul class="collapse">
  <li><a href="#bibliotecas" id="toc-bibliotecas" class="nav-link" data-scroll-target="#bibliotecas">Bibliotecas</a></li>
  <li><a href="#base-de-dados" id="toc-base-de-dados" class="nav-link" data-scroll-target="#base-de-dados">Base de Dados</a></li>
  </ul></li>
  <li><a href="#escolhendo-as-variáveis-preditoras" id="toc-escolhendo-as-variáveis-preditoras" class="nav-link" data-scroll-target="#escolhendo-as-variáveis-preditoras">Escolhendo as variáveis preditoras</a>
  <ul class="collapse">
  <li><a href="#correlação" id="toc-correlação" class="nav-link" data-scroll-target="#correlação">Correlação</a></li>
  <li><a href="#valor-p" id="toc-valor-p" class="nav-link" data-scroll-target="#valor-p">Valor-p</a></li>
  </ul></li>
  <li><a href="#ajustes" id="toc-ajustes" class="nav-link" data-scroll-target="#ajustes">Ajustes</a>
  <ul class="collapse">
  <li><a href="#no-óxido-de-nitrogenio-como-variável-preditora" id="toc-no-óxido-de-nitrogenio-como-variável-preditora" class="nav-link" data-scroll-target="#no-óxido-de-nitrogenio-como-variável-preditora"><strong>NO</strong> (Óxido de Nitrogenio) como variável preditora</a></li>
  <li><a href="#nox-óxidos-de-nitrogênio-como-variável-preditora" id="toc-nox-óxidos-de-nitrogênio-como-variável-preditora" class="nav-link" data-scroll-target="#nox-óxidos-de-nitrogênio-como-variável-preditora"><strong>NOX</strong> (Óxidos de Nitrogênio) como variável preditora</a></li>
  <li><a href="#no-e-nox-como-variáveis-preditoras" id="toc-no-e-nox-como-variáveis-preditoras" class="nav-link" data-scroll-target="#no-e-nox-como-variáveis-preditoras"><strong>NO</strong> e <strong>NOX</strong> como variáveis preditoras</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Relátorio - Indicadores Ambientais e Bronquite Aguda</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="pré-requisitos" class="level2">
<h2 class="anchored" data-anchor-id="pré-requisitos">Pré-requisitos</h2>
<section id="bibliotecas" class="level3">
<h3 class="anchored" data-anchor-id="bibliotecas">Bibliotecas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(glarma)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(performance)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(kableExtra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(Hmisc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="base-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="base-de-dados">Base de Dados</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"Data_CPDO.txt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="escolhendo-as-variáveis-preditoras" class="level2">
<h2 class="anchored" data-anchor-id="escolhendo-as-variáveis-preditoras">Escolhendo as variáveis preditoras</h2>
<section id="correlação" class="level3">
<h3 class="anchored" data-anchor-id="correlação">Correlação</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>poluentes <span class="ot">&lt;-</span> df[, <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>matrix <span class="ot">&lt;-</span>  <span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(poluentes))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> matrix<span class="sc">$</span>r</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>p_value_matrix <span class="ot">&lt;-</span> matrix<span class="sc">$</span>P</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>cor_matrix[<span class="fu">lower.tri</span>(cor_matrix, <span class="at">diag =</span> <span class="cn">TRUE</span>)] <span class="ot">&lt;-</span> <span class="st">""</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>p_value_matrix[<span class="fu">lower.tri</span>(p_value_matrix, <span class="at">diag =</span> <span class="cn">TRUE</span>)] <span class="ot">&lt;-</span> <span class="st">""</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Usando a função <code>rcorr</code> do pacote <code>Hmisc</code>, é possivel criar uma tabela de correlação entre a variável resposta (bronquite aguda) e as variáveis preditoras (poluentes).</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">bronq_aguda</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">CO</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">PM10</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NO</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NO2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NOX</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">O3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Temp_min</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">RH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bronq_aguda</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.0323432810141658</td>
<td style="text-align: center;">0.0756939563571763</td>
<td style="text-align: center;">0.297721005846306</td>
<td style="text-align: center;">-0.0271288307911392</td>
<td style="text-align: center;">0.18245089799302</td>
<td style="text-align: center;">-0.348436360834819</td>
<td style="text-align: center;">-0.147503841432864</td>
<td style="text-align: center;">0.109359895741852</td>
</tr>
<tr class="even">
<td style="text-align: left;">CO</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.150395505169633</td>
<td style="text-align: center;">0.102595870518991</td>
<td style="text-align: center;">0.153471436405583</td>
<td style="text-align: center;">0.141098015100781</td>
<td style="text-align: center;">0.0705832464671625</td>
<td style="text-align: center;">-0.129452742871646</td>
<td style="text-align: center;">0.116940892551031</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PM10</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.470265202892027</td>
<td style="text-align: center;">0.294727543313694</td>
<td style="text-align: center;">0.449074960064434</td>
<td style="text-align: center;">0.366315194645902</td>
<td style="text-align: center;">-0.444210236387916</td>
<td style="text-align: center;">-0.520590928460985</td>
</tr>
<tr class="even">
<td style="text-align: left;">NO</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.518064025162367</td>
<td style="text-align: center;">0.909032460101456</td>
<td style="text-align: center;">-0.186500223569621</td>
<td style="text-align: center;">-0.484465479347949</td>
<td style="text-align: center;">-0.184498031508502</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NO2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.826639563204768</td>
<td style="text-align: center;">0.239468345698813</td>
<td style="text-align: center;">-0.205333770787192</td>
<td style="text-align: center;">-0.249814235591937</td>
</tr>
<tr class="even">
<td style="text-align: left;">NOX</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0126237025596161</td>
<td style="text-align: center;">-0.410682660455583</td>
<td style="text-align: center;">-0.238506628340795</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.0416076775561365</td>
<td style="text-align: center;">-0.56800320581987</td>
</tr>
<tr class="even">
<td style="text-align: left;">Temp_min</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.479085422929526</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RH</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>A matrix apresenta as correlações entre diferentes variáveis ambientais e de saúde, com foco na relação com a bronquite aguda. Os coeficientes de correlação variam de -1 a 1, indicando a força e a direção da relação entre duas variáveis.</p>
<ul>
<li>A bronquite aguda está positivamente correlacionada com poluentes como <span class="math inline">\(\text{NO}\)</span> e <span class="math inline">\(\text{NOX}\)</span>, o que reforça a ligação entre poluição atmosférica e problemas respiratórios.</li>
<li>Níveis de <span class="math inline">\(\text{O3}\)</span> têm uma correlação negativa com bronquite aguda, indicando que pode haver um efeito protetor em certos contextos.</li>
<li>A <strong>umidade relativa</strong> apresenta relação moderada com poluentes e saúde, possivelmente modulando a dispersão de partículas no ar.</li>
</ul>
</section>
<section id="valor-p" class="level3">
<h3 class="anchored" data-anchor-id="valor-p">Valor-p</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">bronq_aguda</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">CO</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">PM10</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NO</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NO2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">NOX</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">O3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Temp_min</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">RH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bronq_aguda</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.770236313565127</td>
<td style="text-align: center;">0.493764095978874</td>
<td style="text-align: center;">0.0059515516139339</td>
<td style="text-align: center;">0.806487924104706</td>
<td style="text-align: center;">0.0966916248868777</td>
<td style="text-align: center;">0.00116199965294816</td>
<td style="text-align: center;">0.18057863922756</td>
<td style="text-align: center;">0.322049180669552</td>
</tr>
<tr class="even">
<td style="text-align: left;">CO</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.172088198793251</td>
<td style="text-align: center;">0.353059677829768</td>
<td style="text-align: center;">0.16338248838001</td>
<td style="text-align: center;">0.20046661153902</td>
<td style="text-align: center;">0.523467526006617</td>
<td style="text-align: center;">0.240546364305547</td>
<td style="text-align: center;">0.289435253017851</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PM10</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">6.37303131445499e-06</td>
<td style="text-align: center;">0.00649902949122572</td>
<td style="text-align: center;">1.82972428215411e-05</td>
<td style="text-align: center;">0.000610362604302583</td>
<td style="text-align: center;">2.30840805004462e-05</td>
<td style="text-align: center;">3.85227497901042e-07</td>
</tr>
<tr class="even">
<td style="text-align: left;">NO</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">4.48394607666103e-07</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0893891178586657</td>
<td style="text-align: center;">3.01917433187526e-06</td>
<td style="text-align: center;">0.092943393326975</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NO2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0282422382101319</td>
<td style="text-align: center;">0.0609669139552675</td>
<td style="text-align: center;">0.0219204252375538</td>
</tr>
<tr class="even">
<td style="text-align: left;">NOX</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.909262320520265</td>
<td style="text-align: center;">0.000104361487907489</td>
<td style="text-align: center;">0.0289012973958713</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.707073384795892</td>
<td style="text-align: center;">1.74993681767432e-08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Temp_min</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">4.02276326205708e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RH</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>A matriz de valores-p foi utilizada para avaliar a significância estatística das correlações observadas anteriormente. Valores-p menores que <strong>0,05</strong> indicam uma relação estatisticamente significativa, enquanto valores maiores sugerem que a correlação pode ser atribuída ao acaso.</p>
<ul>
<li><p>As relações entre <span class="math inline">\(\text{NO}\)</span> e bronquite aguda (<span class="math inline">\(\text{p = 0,0059}\)</span>) e entre <span class="math inline">\(\text{O3}\)</span> e bronquite aguda ( <span class="math inline">\(\text{p = 0,0012}\)</span>) são as mais significativas.</p></li>
<li><p>Poluentes como <span class="math inline">\(\text{PM10}\)</span> e <span class="math inline">\(\text{NO}\)</span> mostram forte interação com variáveis ambientais como umidade e temperatura, mas nem todas têm impacto direto na saúde com significância estatística.</p></li>
<li><p>Embora várias variáveis tenham correlações aparentes com a bronquite aguda, apenas algumas relações são estatisticamente robustas.</p></li>
<li><p>A relação entre <span class="math inline">\(\text{umidade relativa}\)</span> e poluentes como <span class="math inline">\(\text{PM10}\)</span> é estatisticamente significativa e pode influenciar a dispersão de partículas no ar.</p></li>
</ul>
</section>
</section>
<section id="ajustes" class="level2">
<h2 class="anchored" data-anchor-id="ajustes">Ajustes</h2>
<section id="no-óxido-de-nitrogenio-como-variável-preditora" class="level3">
<h3 class="anchored" data-anchor-id="no-óxido-de-nitrogenio-como-variável-preditora"><strong>NO</strong> (Óxido de Nitrogenio) como variável preditora</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> df[,<span class="dv">1</span>]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(df[,<span class="dv">4</span>])</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>Trend <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">84</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>Intercepto <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">84</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Intercepto, Trend, X1, df<span class="sc">$</span>cos6, df<span class="sc">$</span>cos12, df<span class="sc">$</span>sen6, df<span class="sc">$</span>sen12)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(X1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Intercepto"</span>, <span class="st">"Trend"</span>, <span class="st">"NO"</span>, <span class="st">"cos6"</span>, <span class="st">"cos12"</span>, <span class="st">"sen6"</span>, <span class="st">"sen12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="glarma-binomial-negativo" class="level4">
<h4 class="anchored" data-anchor-id="glarma-binomial-negativo">GLARMA Binomial Negativo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>glarma_nb <span class="ot">&lt;-</span> <span class="fu">glarma</span>(y, X1, <span class="at">thetaLags =</span> <span class="cn">NULL</span>, <span class="at">phiLags =</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"NegBin"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"FS"</span>, <span class="at">residuals=</span> <span class="st">"Pearson"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">maxit =</span> <span class="dv">100</span>, <span class="at">grad =</span> <span class="fl">1e-6</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: glarma(y = y, X = X1, type = "NegBin", method = "FS", residuals = "Pearson", 
    phiLags = 1, thetaLags = NULL, maxit = 100, grad = 1e-06)

Pearson Residuals:
    Min       1Q   Median       3Q      Max  
-2.4856  -0.8947  -0.1203   0.5752   4.0168  

Negative Binomial Parameter:
      Estimate Std.Error z-ratio Pr(&gt;|z|)    
alpha   14.813     3.786   3.912 9.15e-05 ***

GLARMA Coefficients:
      Estimate Std.Error z-ratio Pr(&gt;|z|)    
phi_1  0.22406   0.03985   5.623 1.88e-08 ***

Linear Model Coefficients:
            Estimate Std.Error z-ratio Pr(&gt;|z|)    
Intercepto  3.180309  0.121089  26.264  &lt; 2e-16 ***
Trend       0.008510  0.001942   4.382 1.18e-05 ***
NO          0.019641  0.006340   3.098  0.00195 ** 
cos6       -0.065614  0.060498  -1.085  0.27812    
cos12      -0.454707  0.073249  -6.208 5.38e-10 ***
sen6       -0.315997  0.056916  -5.552 2.82e-08 ***
sen12       0.466171  0.063349   7.359 1.86e-13 ***

    Null deviance: 361.607  on 83  degrees of freedom
Residual deviance:  98.288  on 75  degrees of freedom
AIC: 687.9201 

Number of Fisher Scoring iterations: 100

LRT and Wald Test:
Alternative hypothesis: model is a GLARMA process
Null hypothesis: model is a GLM with the same regression structure
          Statistic  p-value    
LR Test       25.22 5.11e-07 ***
Wald Test     31.62 1.88e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>O modelo GLARMA com distribuição Binomial Negativa foi ajustado para capturar as características estruturais e temporais dos dados de contagem analisados. Os resultados indicam que o modelo é estatisticamente robusto e apropriado para os dados, conforme evidenciado pelos seguintes pontos principais:</p>
<ol type="1">
<li><p><strong>Adequação do modelo Binomial Negativa:</strong><br>
O parâmetro de dispersão (<span class="math inline">\(\alpha = 14.813\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) demonstra que os dados apresentam superdispersão significativa, justificando a escolha da distribuição Binomial Negativa em vez da Poisson.</p></li>
<li><p><strong>Dependência temporal:</strong><br>
O coeficiente (<span class="math inline">\(\phi_1= 0.22406\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) confirma a presença de dependência temporal nos dados, com eventos passados influenciando os valores futuros. Isso valida a necessidade do componente autorregressivo do modelo GLARMA.</p></li>
<li><p><strong>Impacto das variáveis explicativas:</strong></p>
<ul>
<li>A tendência (<span class="math inline">\(\text{Trend} = 0.00851\)</span> , <span class="math inline">\(p &lt; 0.001\)</span>) indica um aumento consistente na contagem esperada ao longo do tempo.</li>
<li>A variável (<span class="math inline">\(\text{NO} = 0.01964\)</span>, <span class="math inline">\(p = 0.00195\)</span> ) tem um impacto positivo significativo, aumentando a contagem esperada.</li>
<li>Os componentes sazonais (<span class="math inline">\(\cos(12)\)</span>, <span class="math inline">\(\sin(6)\)</span> e <span class="math inline">\(\sin(12)\)</span> são altamente significativos, confirmando a presença de padrões sazonais nos dados.</li>
</ul></li>
<li><p><strong>Qualidade do ajuste:</strong><br>
O modelo apresenta uma redução substancial na deviance residual (98.288) em relação à deviance nula (361.607), indicando que ele explica bem os dados. Além disso, o menor AIC (687.92) em comparação ao modelo Poisson sugere que o modelo Binomial Negativa é mais adequado para capturar a variabilidade nos dados.</p></li>
<li><p><strong>Validação do modelo GLARMA:</strong><br>
Os testes de razão de verossimilhança (LRT) e de Wald (<span class="math inline">\(p &lt; 0.001\)</span>) indicam que o modelo GLARMA é significativamente superior a um modelo GLM simples com a mesma estrutura de regressão.</p></li>
</ol>
<p>O modelo GLARMA com Binomial Negativa ajustou adequadamente os dados, capturando tanto a superdispersão quanto a dependência temporal. As variáveis sazonais e a tendência mostraram-se fatores determinantes para explicar a variabilidade nas contagens, reforçando a relevância do modelo para a análise dos dados. A ausência de correlações nos resíduos sugere que as estruturas remanescentes foram bem modeladas, tornando o modelo adequado para interpretações e previsões confiáveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glarma_nb<span class="sc">$</span>residuals)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glarma_nb<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os gráficos de ACF e PACF dos resíduos do modelo GLARMA mostram que as autocorrelações estão dentro das bandas de confiança. Isso indica que os resíduos não apresentam correlação significativa entre os atrasos e se comportam como um ruído branco. Portanto, podemos concluir que o modelo capturou adequadamente as dependências temporais e estruturais presentes nos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Com base nos resultados apresentados, podemos avaliar a adequação do modelo GLARMA aos dados observados:</p>
<ol type="1">
<li><p><strong>Aderência aos Dados Observados</strong>: O modelo ajustado utilizando GLARMA demonstrou ser eficaz ao reproduzir os padrões temporais das contagens observadas. Isso foi confirmado pela similaridade entre as linhas representando os valores observados (preta) e ajustados (vermelha). O desempenho foi consistentemente superior ao obtido com valores fixos (linha azul), validando a capacidade do modelo de capturar a dinâmica dos dados.</p></li>
<li><p><strong>Resíduos de Pearson</strong>: A inspeção dos resíduos de Pearson revelou a ausência de tendências ou sazonalidades claras, sugerindo que o modelo explicou bem a variabilidade dos dados sem introduzir vieses sistemáticos.</p></li>
<li><p><strong>Distribuição do PIT</strong>: Apesar de o histograma do Probability Integral Transform (PIT) não apresentar uma uniformidade ideal, não foram detectados padrões críticos que comprometessem a validade do modelo. Isso indica que o ajuste está suficientemente adequado para descrever os dados.</p></li>
<li><p><strong>Distribuição e Normalidade dos Resíduos Randomizados</strong>: O histograma dos resíduos randomizados apresentou desvios em relação à normalidade ideal, mas o Q-Q Plot indicou que, em geral, os resíduos seguem uma distribuição aproximadamente normal, sem desvios graves. Embora haja espaço para melhorias, os resultados são aceitáveis.</p></li>
<li><p><strong>Dependência Temporal</strong>: A análise da função de autocorrelação (ACF) dos resíduos randomizados mostrou valores dentro dos intervalos de confiança, confirmando que o modelo capturou de forma satisfatória a dependência temporal dos dados.</p></li>
</ol>
<p>De forma geral, o modelo GLARMA demonstrou boa adequação aos dados analisados, apesar de algumas limitações observadas, como os desvios nos resíduos randomizados. Recomenda-se uma análise mais aprofundada desses pontos e, se necessário, ajustes no modelo ou a inclusão de variáveis adicionais. Ainda assim, o modelo atual é confiável e robusto para atender aos objetivos de interpretação e predição propostos.</p>
</section>
</section>
<section id="nox-óxidos-de-nitrogênio-como-variável-preditora" class="level3">
<h3 class="anchored" data-anchor-id="nox-óxidos-de-nitrogênio-como-variável-preditora"><strong>NOX</strong> (Óxidos de Nitrogênio) como variável preditora</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> df[,<span class="dv">1</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(df[,<span class="dv">6</span>])</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>Trend <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">84</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>Intercepto <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">84</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Intercepto, Trend, X2, df<span class="sc">$</span>cos6, df<span class="sc">$</span>cos12, df<span class="sc">$</span>sen6, df<span class="sc">$</span>sen12)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(X2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Intercepto"</span>, <span class="st">"Trend"</span>, <span class="st">"NOX"</span>, <span class="st">"cos6"</span>, <span class="st">"cos12"</span>, <span class="st">"sen6"</span>, <span class="st">"sen12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="glarma-binomial-negativo-1" class="level4">
<h4 class="anchored" data-anchor-id="glarma-binomial-negativo-1">GLARMA Binomial Negativo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>glarma_nb <span class="ot">&lt;-</span> <span class="fu">glarma</span>(y, X2, <span class="at">thetaLags =</span> <span class="cn">NULL</span>, <span class="at">phiLags =</span> <span class="dv">1</span>, <span class="at">type =</span> <span class="st">"NegBin"</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"FS"</span>, <span class="at">residuals=</span> <span class="st">"Pearson"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">maxit =</span> <span class="dv">100</span>, <span class="at">grad =</span> <span class="fl">1e-6</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: glarma(y = y, X = X2, type = "NegBin", method = "FS", residuals = "Pearson", 
    phiLags = 1, thetaLags = NULL, maxit = 100, grad = 1e-06)

Pearson Residuals:
    Min       1Q   Median       3Q      Max  
-2.4871  -0.9015  -0.0022   0.4446   3.8532  

Negative Binomial Parameter:
      Estimate Std.Error z-ratio Pr(&gt;|z|)    
alpha   14.990     3.509   4.272 1.94e-05 ***

GLARMA Coefficients:
      Estimate Std.Error z-ratio Pr(&gt;|z|)    
phi_1  0.22132   0.04094   5.407 6.42e-08 ***

Linear Model Coefficients:
            Estimate Std.Error z-ratio Pr(&gt;|z|)    
Intercepto  3.079970  0.140890  21.861  &lt; 2e-16 ***
Trend       0.008068  0.002014   4.006 6.17e-05 ***
NOX         0.012800  0.003681   3.478 0.000506 ***
cos6       -0.052588  0.061898  -0.850 0.395549    
cos12      -0.475997  0.073854  -6.445 1.16e-10 ***
sen6       -0.318841  0.057635  -5.532 3.16e-08 ***
sen12       0.500643  0.065389   7.656 1.91e-14 ***

    Null deviance: 350.697  on 83  degrees of freedom
Residual deviance:  95.115  on 75  degrees of freedom
AIC: 688.6466 

Number of Fisher Scoring iterations: 100

LRT and Wald Test:
Alternative hypothesis: model is a GLARMA process
Null hypothesis: model is a GLM with the same regression structure
          Statistic  p-value    
LR Test       27.21 1.82e-07 ***
Wald Test     29.23 6.42e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>O modelo GLARMA com distribuição Binomial Negativa foi ajustado para examinar os dados de contagem, considerando tanto a superdispersão quanto a dependência temporal. A análise dos resultados revela os seguintes pontos principais:</p>
<ol type="1">
<li><strong>Adequação do modelo Binomial Negativa:</strong>
<ul>
<li>O parâmetro de dispersão <span class="math inline">\(\alpha = 14.813\)</span> (p-valor <span class="math inline">\(&lt; 0.001\)</span>) indica que os dados apresentam superdispersão significativa, o que justifica a escolha da distribuição Binomial Negativa em vez da Poisson. A alta significância deste parâmetro reforça a presença de variabilidade excessiva nos dados.</li>
</ul></li>
<li><strong>Dependência temporal:</strong>
<ul>
<li>O coeficiente <span class="math inline">\(\phi_1 = 0.22406\)</span> (p-valor <span class="math inline">\(&lt; 0.001\)</span>) é significativamente positivo, sugerindo que há uma dependência temporal entre os valores, ou seja, os valores passados influenciam os valores futuros, o que é característico de um modelo GLARMA.</li>
</ul></li>
<li><strong>Impacto das variáveis explicativas:</strong>
<ul>
<li><strong>Intercepto (3.1803,</strong> <span class="math inline">\(p &lt; 2e-16\)</span>): O valor do intercepto é altamente significativo, indicando o nível de contagem esperado quando todas as outras variáveis independentes são zero.</li>
<li><strong>Trend (0.00851,</strong> <span class="math inline">\(p = 1.18e-05\)</span>): A variável de tendência é significativa e sugere que a contagem esperada aumenta de forma constante ao longo do tempo.</li>
<li><strong>NO (0.01964,</strong> <span class="math inline">\(p = 0.00195\)</span>): A variável <span class="math inline">\(\text{NO}\)</span> tem um impacto positivo significativo na contagem esperada, aumentando-a em aproximadamente 1.98% por unidade de aumento em <span class="math inline">\(\text{NO}\)</span>.</li>
<li><strong>cos6 (-0.0656,</strong> <span class="math inline">\(p = 0.278\)</span>): A variável <span class="math inline">\(\cos(6)\)</span> não apresenta significância estatística, sugerindo que o padrão sazonal com período de 6 unidades não afeta de forma relevante a contagem.</li>
<li><strong>cos12 (-0.4547,</strong> <span class="math inline">\(p &lt; 2e-16\)</span>): A variável <span class="math inline">\(\cos(12)\)</span> apresenta um impacto significativo, indicando que o padrão sazonal com período de 12 unidades reduz a contagem esperada.</li>
<li><strong>sen6 (-0.3160,</strong> <span class="math inline">\(p = 2.82e-08\)</span>) e <strong>sen12 (0.4662,</strong> <span class="math inline">\(p = 1.86e-13\)</span>): Ambas as variáveis sazonais são altamente significativas. O termo <span class="math inline">\(\sin(6)\)</span> reduz a contagem esperada, enquanto <span class="math inline">\(\sin(12)\)</span> a aumenta, sugerindo efeitos sazonais opostos.</li>
</ul></li>
<li><strong>Qualidade do ajuste:</strong>
<ul>
<li>A <strong>deviance nula</strong> (361.607) e a <strong>deviance residual</strong> (98.288) indicam que o modelo conseguiu explicar uma parte substancial da variabilidade nos dados. A diferença significativa entre essas duas deviance sugere um bom ajuste.</li>
<li>O <strong>AIC = 687.92</strong> é comparativamente baixo, indicando que o modelo Binomial Negativa se ajusta bem aos dados em relação a alternativas mais simples, como o modelo Poisson.</li>
</ul></li>
<li><strong>Validação do modelo GLARMA:</strong>
<ul>
<li>O <strong>teste de razão de verossimilhança (LRT)</strong> e o <strong>teste de Wald</strong> (ambos com p-valores <span class="math inline">\(&lt; 0.001\)</span>) demonstram que o modelo GLARMA é significativamente superior a um modelo GLM simples com a mesma estrutura de regressão, justificando a escolha do modelo GLARMA para capturar a dependência temporal nos dados.</li>
</ul></li>
</ol>
<p>O modelo GLARMA com Binomial Negativa apresentou um bom ajuste aos dados, com a identificação de superdispersão e dependência temporal significativa. As variáveis explicativas, como a tendência, <span class="math inline">\(\text{NOX}\)</span>, e os componentes sazonais, desempenham papéis cruciais na explicação da variabilidade nas contagens. A presença de uma dependência temporal significativa foi confirmada pelo coeficiente <span class="math inline">\(\phi_1\)</span>. A ausência de correlação nos resíduos e os bons resultados nos testes de validação indicam que o modelo é robusto e adequado para análise e previsão dos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glarma_nb<span class="sc">$</span>residuals)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glarma_nb<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os gráficos de ACF e PACF dos resíduos do modelo GLARMA mostram que as autocorrelações estão dentro das bandas de confiança. Isso indica que os resíduos não apresentam correlação significativa entre os atrasos e se comportam como um ruído branco. Portanto, podemos concluir que o modelo capturou adequadamente as dependências temporais e estruturais presentes nos dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Com base nos resultados apresentados, podemos avaliar a adequação do modelo GLARMA aos dados observados:</p>
<ol type="1">
<li><p><strong>Aderência aos Dados Observados</strong>: O modelo ajustado pelo GLARMA mostrou-se eficiente ao capturar o padrão temporal das contagens observadas, conforme evidenciado pela boa concordância entre as linhas preta (observada) e vermelha (ajustada). O desempenho foi consistentemente superior aos valores fixos (linha azul), reforçando a validade do modelo.</p></li>
<li><p><strong>Resíduos de Pearson</strong>: A análise dos resíduos de Pearson indicou ausência de padrões evidentes (como tendências ou sazonalidades), sugerindo que o modelo foi capaz de explicar bem a variabilidade dos dados sem viés sistemático.</p></li>
<li><p><strong>Distribuição do PIT</strong>: O histograma do Probability Integral Transform (PIT) não apresentou uniformidade perfeita, mas também não revelou padrões preocupantes, indicando que o modelo pode estar suficientemente ajustado para descrever os dados.</p></li>
<li><p><strong>Distribuição e Normalidade dos Resíduos Randomizados</strong>: Apesar de o histograma dos resíduos randomizados mostrar desvios em relação a uma distribuição normal ideal, o Q-Q Plot sugeriu que os resíduos estão aproximadamente normais, sem desvios severos. Esses resultados sugerem que o modelo é aceitável, embora melhorias possam ser exploradas.</p></li>
<li><p><strong>Dependência Temporal</strong>: A análise da autocorrelação (ACF) dos resíduos randomizados revelou que os valores estão dentro dos intervalos de confiança, indicando que o modelo capturou adequadamente a estrutura de dependência temporal dos dados.</p></li>
</ol>
<p>Embora os resultados gerais apontem para um bom ajuste do modelo GLARMA, algumas limitações foram observadas, como os desvios na distribuição dos resíduos randomizados. Recomenda-se uma investigação mais detalhada desses aspectos, considerando a possibilidade de refinar o modelo ou explorar variáveis adicionais para melhorar o ajuste.</p>
<p>No entanto, considerando os objetivos propostos e as análises realizadas, o modelo atual pode ser considerado robusto para a interpretação e predição dos dados analisados.</p>
</section>
</section>
<section id="no-e-nox-como-variáveis-preditoras" class="level3">
<h3 class="anchored" data-anchor-id="no-e-nox-como-variáveis-preditoras"><strong>NO</strong> e <strong>NOX</strong> como variáveis preditoras</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> df[,<span class="dv">1</span>]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(df[,<span class="dv">4</span>])</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(df[,<span class="dv">7</span>])</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Trend <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">84</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>Intercepto <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">84</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>X3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Intercepto, Trend, X1, X2, df<span class="sc">$</span>cos6, df<span class="sc">$</span>cos12, df<span class="sc">$</span>sen6, df<span class="sc">$</span>sen12)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(X3) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Intercepto"</span>, <span class="st">"Trend"</span>, <span class="st">"NO"</span>, <span class="st">"O3"</span>, <span class="st">"cos6"</span>, <span class="st">"cos12"</span>, <span class="st">"sen6"</span>, <span class="st">"sen12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="glarma-binomial-negativo-2" class="level4">
<h4 class="anchored" data-anchor-id="glarma-binomial-negativo-2">GLARMA Binomial Negativo</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>glarma_nb <span class="ot">&lt;-</span> <span class="fu">glarma</span>(y, X3, <span class="at">thetaLags =</span> <span class="cn">NULL</span>, <span class="at">phiLags =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">12</span>), <span class="at">type =</span> <span class="st">"NegBin"</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"FS"</span>, <span class="at">residuals=</span> <span class="st">"Pearson"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">maxit =</span> <span class="dv">100</span>, <span class="at">grad =</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: glarma(y = y, X = X3, type = "NegBin", method = "FS", residuals = "Pearson", 
    phiLags = c(3, 12), thetaLags = NULL, maxit = 100, grad = 1e-06)

Pearson Residuals:
    Min       1Q   Median       3Q      Max  
-1.6391  -0.8543  -0.0158   0.9772   3.6886  

Negative Binomial Parameter:
      Estimate Std.Error z-ratio Pr(&gt;|z|)   
alpha    8.908     2.911    3.06  0.00221 **

GLARMA Coefficients:
       Estimate Std.Error z-ratio Pr(&gt;|z|)  
phi_3  -0.02492   0.03338  -0.747   0.4552  
phi_12 -0.06751   0.03447  -1.959   0.0502 .

Linear Model Coefficients:
            Estimate Std.Error z-ratio Pr(&gt;|z|)    
Intercepto  3.409108  0.189199  18.019  &lt; 2e-16 ***
Trend       0.007727  0.001413   5.468 4.54e-08 ***
NO          0.027952  0.009071   3.082  0.00206 ** 
O3         -0.020023  0.010468  -1.913  0.05576 .  
cos6       -0.185255  0.059546  -3.111  0.00186 ** 
cos12      -0.385247  0.059535  -6.471 9.74e-11 ***
sen6       -0.377309  0.057725  -6.536 6.30e-11 ***
sen12       0.410284  0.066029   6.214 5.18e-10 ***

    Null deviance: 363.88  on 83  degrees of freedom
Residual deviance: 106.41  on 73  degrees of freedom
AIC: 720.2555 

Number of Fisher Scoring iterations: 100

LRT and Wald Test:
Alternative hypothesis: model is a GLARMA process
Null hypothesis: model is a GLM with the same regression structure
          Statistic p-value  
LR Test      -3.767  1.0000  
Wald Test     4.783  0.0915 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Como o <strong>NO</strong> e o <strong>NOX</strong> tem alta correlação, o ajuste do modelo usando as duas variáveis é inviavél.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glarma_nb<span class="sc">$</span>residuals)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glarma_nb<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>