<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Relátorio - Casos de Poliomielite – Relatórios IC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Relatórios IC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Sobre</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/cheriroga/relatorios"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pré-requisitos" id="toc-pré-requisitos" class="nav-link active" data-scroll-target="#pré-requisitos">Pré-requisitos</a>
  <ul class="collapse">
  <li><a href="#bibliotecas" id="toc-bibliotecas" class="nav-link" data-scroll-target="#bibliotecas">Bibliotecas</a></li>
  <li><a href="#base-de-dados" id="toc-base-de-dados" class="nav-link" data-scroll-target="#base-de-dados">Base de dados</a></li>
  </ul></li>
  <li><a href="#variáveis" id="toc-variáveis" class="nav-link" data-scroll-target="#variáveis">Variáveis</a></li>
  <li><a href="#ajuste-do-modelo-glm-poisson" id="toc-ajuste-do-modelo-glm-poisson" class="nav-link" data-scroll-target="#ajuste-do-modelo-glm-poisson">Ajuste do Modelo GLM Poisson</a>
  <ul class="collapse">
  <li><a href="#ajuste-do-modelo" id="toc-ajuste-do-modelo" class="nav-link" data-scroll-target="#ajuste-do-modelo">Ajuste do Modelo</a></li>
  <li><a href="#summary-do-modelo" id="toc-summary-do-modelo" class="nav-link" data-scroll-target="#summary-do-modelo">Summary do Modelo</a></li>
  <li><a href="#análise-dos-resíduos-do-modelo" id="toc-análise-dos-resíduos-do-modelo" class="nav-link" data-scroll-target="#análise-dos-resíduos-do-modelo">Análise dos Resíduos do Modelo</a></li>
  </ul></li>
  <li><a href="#conclusão-do-modelo-glm-poisson" id="toc-conclusão-do-modelo-glm-poisson" class="nav-link" data-scroll-target="#conclusão-do-modelo-glm-poisson">Conclusão do Modelo GLM Poisson</a></li>
  <li><a href="#ajuste-do-modelo-glm-binomial-negativo" id="toc-ajuste-do-modelo-glm-binomial-negativo" class="nav-link" data-scroll-target="#ajuste-do-modelo-glm-binomial-negativo">Ajuste do Modelo GLM Binomial Negativo</a>
  <ul class="collapse">
  <li><a href="#ajuste-do-modelo-1" id="toc-ajuste-do-modelo-1" class="nav-link" data-scroll-target="#ajuste-do-modelo-1">Ajuste do Modelo</a></li>
  <li><a href="#summary-do-modelo-1" id="toc-summary-do-modelo-1" class="nav-link" data-scroll-target="#summary-do-modelo-1">Summary do Modelo</a></li>
  <li><a href="#análise-dos-resíduos-do-modelo-binomial-negativo" id="toc-análise-dos-resíduos-do-modelo-binomial-negativo" class="nav-link" data-scroll-target="#análise-dos-resíduos-do-modelo-binomial-negativo">Análise dos Resíduos do Modelo Binomial Negativo</a></li>
  <li><a href="#conclusão-do-modelo-glm-binomial-negativo" id="toc-conclusão-do-modelo-glm-binomial-negativo" class="nav-link" data-scroll-target="#conclusão-do-modelo-glm-binomial-negativo">Conclusão do Modelo GLM Binomial Negativo</a></li>
  </ul></li>
  <li><a href="#ajuste-do-modelo-glarma-poisson" id="toc-ajuste-do-modelo-glarma-poisson" class="nav-link" data-scroll-target="#ajuste-do-modelo-glarma-poisson">Ajuste do Modelo GLARMA Poisson</a>
  <ul class="collapse">
  <li><a href="#summary-do-modelo-2" id="toc-summary-do-modelo-2" class="nav-link" data-scroll-target="#summary-do-modelo-2">Summary do Modelo</a></li>
  <li><a href="#análise-dos-resíduos-do-modelo-1" id="toc-análise-dos-resíduos-do-modelo-1" class="nav-link" data-scroll-target="#análise-dos-resíduos-do-modelo-1">Análise dos Resíduos do Modelo</a></li>
  </ul></li>
  <li><a href="#conclusão-do-modelo-glarma-poisson" id="toc-conclusão-do-modelo-glarma-poisson" class="nav-link" data-scroll-target="#conclusão-do-modelo-glarma-poisson">Conclusão do Modelo GLARMA Poisson</a></li>
  <li><a href="#ajuste-do-modelo-glarma-binomial-negativo" id="toc-ajuste-do-modelo-glarma-binomial-negativo" class="nav-link" data-scroll-target="#ajuste-do-modelo-glarma-binomial-negativo">Ajuste do Modelo GLARMA Binomial Negativo</a>
  <ul class="collapse">
  <li><a href="#summary-do-modelo-3" id="toc-summary-do-modelo-3" class="nav-link" data-scroll-target="#summary-do-modelo-3">Summary do Modelo</a></li>
  <li><a href="#análise-dos-resíduos-do-modelo-2" id="toc-análise-dos-resíduos-do-modelo-2" class="nav-link" data-scroll-target="#análise-dos-resíduos-do-modelo-2">Análise dos Resíduos do Modelo</a></li>
  <li><a href="#conclusão-do-modelo-glarma-binomial-negativo" id="toc-conclusão-do-modelo-glarma-binomial-negativo" class="nav-link" data-scroll-target="#conclusão-do-modelo-glarma-binomial-negativo">Conclusão do Modelo GLARMA Binomial Negativo</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Relátorio - Casos de Poliomielite</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="pré-requisitos" class="level2">
<h2 class="anchored" data-anchor-id="pré-requisitos">Pré-requisitos</h2>
<section id="bibliotecas" class="level3">
<h3 class="anchored" data-anchor-id="bibliotecas">Bibliotecas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glarma)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="base-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="base-de-dados">Base de dados</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Polio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="variáveis" class="level2">
<h2 class="anchored" data-anchor-id="variáveis">Variáveis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(Polio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 168
Columns: 8
$ RowNames      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ Cases         &lt;int&gt; 0, 1, 0, 0, 1, 3, 9, 2, 3, 5, 3, 5, 2, 2, 0, 1, 0, 1, 3,…
$ Intcpt        &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ Trend         &lt;dbl&gt; -0.072, -0.071, -0.070, -0.069, -0.068, -0.067, -0.066, …
$ CosAnnual     &lt;dbl&gt; 1.000000e+00, 8.660254e-01, 5.000000e-01, -3.184654e-15,…
$ SinAnnual     &lt;dbl&gt; 1.469528e-15, 5.000000e-01, 8.660254e-01, 1.000000e+00, …
$ CosSemiAnnual &lt;dbl&gt; 1.0, 0.5, -0.5, -1.0, -0.5, 0.5, 1.0, 0.5, -0.5, -1.0, -…
$ SinSemiAnnual &lt;dbl&gt; 2.939055e-15, 8.660254e-01, 8.660254e-01, -6.369308e-15,…</code></pre>
</div>
</div>
<ul>
<li><strong>Variável resposta:</strong> <code>Cases</code></li>
<li><strong>Variáveis preditoras:</strong> <code>Intcpt</code>, <code>Trend</code>, <code>CosAnnual</code>, <code>SinAnnual</code>, <code>CosSemiAnnual</code>, <code>SinSemiAnnual</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> Polio[, <span class="dv">2</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(Polio[, <span class="dv">3</span><span class="sc">:</span><span class="dv">8</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ajuste-do-modelo-glm-poisson" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-do-modelo-glm-poisson">Ajuste do Modelo GLM Poisson</h2>
<section id="ajuste-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="ajuste-do-modelo">Ajuste do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>glm_poi <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> X, <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="summary-do-modelo">Summary do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_poi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ X, family = poisson(link = "log"))

Coefficients: (1 not defined because of singularities)
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     0.20694    0.07508   2.756 0.005849 ** 
XIntcpt              NA         NA      NA       NA    
XTrend         -4.79866    1.40289  -3.421 0.000625 ***
XCosAnnual     -0.14873    0.09722  -1.530 0.126037    
XSinAnnual     -0.53188    0.10904  -4.878 1.07e-06 ***
XCosSemiAnnual  0.16910    0.09881   1.711 0.087013 .  
XSinSemiAnnual -0.43214    0.10080  -4.287 1.81e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 343.00  on 167  degrees of freedom
Residual deviance: 288.85  on 162  degrees of freedom
AIC: 557.9

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>O modelo de Poisson revela que <code>XTrend</code>, <code>XSinAnnual</code> e <code>XSinSemiAnnual</code> têm efeitos significativos sobre o número de casos de poliomielite, enquanto <code>XCosAnnual</code> e <code>XCosSemiAnnual</code> não apresentam evidências suficientes de impacto. A análise indica que, embora o modelo de Poisson capture algumas das dinâmicas dos dados, a significância dos coeficientes e o AIC sugerem que ele pode não ser o modelo mais adequado, especialmente considerando que a variância pode ser maior que a média.</p>
</section>
<section id="análise-dos-resíduos-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="análise-dos-resíduos-do-modelo">Análise dos Resíduos do Modelo</h3>
<section id="acf-autocorrelação-e-pacf-autocorrelação-parcial" class="level4">
<h4 class="anchored" data-anchor-id="acf-autocorrelação-e-pacf-autocorrelação-parcial">ACF (Autocorrelação) e PACF (Autocorrelação Parcial)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glm_poi<span class="sc">$</span>residuals)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glm_poi<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/acf_poisson-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os gráficos de ACF e PACF mostram autocorrelação significativa no lag 1, sugerindo dependência temporal nos resíduos e a necessidade de ajustes no modelo.</p>
</section>
<section id="diagnóstico-dos-resíduos" class="level4">
<h4 class="anchored" data-anchor-id="diagnóstico-dos-resíduos">Diagnóstico dos Resíduos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glm_poi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/diag_poisson-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><strong>Resíduos vs Ajustados (Residuals vs Fitted)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Verificar se a variabilidade dos resíduos é aleatória em relação aos valores ajustados.</li>
<li>Interpretação: Se os resíduos mostram um padrão (como uma curva ou tendência), isso sugere que o modelo não está capturando todas as relações nos dados.</li>
<li>Observação: No gráfico, parece haver um leve padrão nos resíduos, sugerindo possível falta de ajuste.</li>
</ul>
<ol start="2" type="1">
<li><strong>Gráfico Q-Q (Q-Q Plot)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Avaliar a normalidade dos resíduos.</li>
<li>Interpretação: Os resíduos devem seguir uma linha reta ao longo da diagonal. Desvios nos extremos indicam que a distribuição dos resíduos não é normal.</li>
<li>Observação: O gráfico mostra que os resíduos desviam da linha reta nos extremos, indicando que a distribuição dos resíduos pode não ser normal, o que é esperado em um modelo de Poisson.</li>
</ul>
<ol start="3" type="1">
<li><strong>Escala-Localização (Scale-Location)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Verificar a homogeneidade da variância (homocedasticidade).</li>
<li>Interpretação: A linha vermelha deve ser aproximadamente horizontal, indicando que a variância dos resíduos é constante. Um padrão ascendente ou descendente indica heterocedasticidade.</li>
<li>Observação: Há um leve padrão ascendente, sugerindo heterocedasticidade (variância não constante).</li>
</ul>
<ol start="4" type="1">
<li><strong>Resíduos vs Alavancagem (Residuals vs Leverage)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Identificar influências indevidas que podem afetar o modelo.</li>
<li>Interpretação: Pontos com resíduos grandes e alta alavancagem podem ser influentes e distorcer os resultados do modelo.</li>
<li>Observação: Há alguns pontos com alta alavancagem e resíduos grandes, o que pode indicar observações influentes.</li>
</ul>
</section>
<section id="testes-de-overdispersion-e-zero-inflation" class="level4">
<h4 class="anchored" data-anchor-id="testes-de-overdispersion-e-zero-inflation">Testes de Overdispersion e Zero Inflation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_overdispersion</span>(glm_poi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Overdispersion test

       dispersion ratio =   1.980
  Pearson's Chi-Squared = 318.722
                p-value = &lt; 0.001</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Overdispersion detected.</code></pre>
</div>
</div>
<p>A razão de dispersão de 1.980 e o p-valor &lt; 0.001 indicam sobre-dispersão. Isso sugere que a variância dos dados é maior que a média, o que é uma condição comum em dados de contagem, reforçando a inadequação do modelo de Poisson.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_zeroinflation</span>(glm_poi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for zero-inflation

   Observed zeros: 64
  Predicted zeros: 53
            Ratio: 0.83</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Model is underfitting zeros (probable zero-inflation).</code></pre>
</div>
</div>
<p>A razão de 0.83 sugere que o modelo não captura adequadamente o excesso de zeros nos dados. A presença de zeros inflacionados pode indicar que o modelo de Poisson não é o mais adequado, uma vez que ele não considera a estrutura de contagem de zeros.</p>
</section>
</section>
</section>
<section id="conclusão-do-modelo-glm-poisson" class="level2">
<h2 class="anchored" data-anchor-id="conclusão-do-modelo-glm-poisson">Conclusão do Modelo GLM Poisson</h2>
<p>O modelo de Poisson apresenta falta de homogeneidade de variância, sobre-dispersão e inflação de zeros, tornando-o inadequado.</p>
<hr>
</section>
<section id="ajuste-do-modelo-glm-binomial-negativo" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-do-modelo-glm-binomial-negativo">Ajuste do Modelo GLM Binomial Negativo</h2>
<section id="ajuste-do-modelo-1" class="level3">
<h3 class="anchored" data-anchor-id="ajuste-do-modelo-1">Ajuste do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>glm_nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(y <span class="sc">~</span> X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary-do-modelo-1" class="level3">
<h3 class="anchored" data-anchor-id="summary-do-modelo-1">Summary do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = y ~ X, init.theta = 1.763244783, link = log)

Coefficients: (1 not defined because of singularities)
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      0.2093     0.0957   2.187 0.028728 *  
XIntcpt              NA         NA      NA       NA    
XTrend          -4.3318     1.8946  -2.286 0.022234 *  
XCosAnnual      -0.1430     0.1287  -1.112 0.266320    
XSinAnnual      -0.5025     0.1379  -3.644 0.000269 ***
XCosSemiAnnual   0.1682     0.1308   1.286 0.198362    
XSinSemiAnnual  -0.4214     0.1324  -3.183 0.001459 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(1.7632) family taken to be 1)

    Null deviance: 201.22  on 167  degrees of freedom
Residual deviance: 171.20  on 162  degrees of freedom
AIC: 521.66

Number of Fisher Scoring iterations: 1

              Theta:  1.763 
          Std. Err.:  0.484 

 2 x log-likelihood:  -507.656 </code></pre>
</div>
</div>
<p>O modelo binomial negativo apresenta coeficientes significativos para algumas variáveis, especialmente <code>XTrend</code>, <code>XSinAnnual</code> e <code>XSinSemiAnnual</code>, sugerindo uma relação importante entre essas variáveis e o número de casos de poliomielite. O modelo também lida bem com a sobre-dispersão nos dados, evidenciado pelo parâmetro theta e pelas deviance. No entanto, a falta de significância em outras variáveis indica que nem todos os fatores considerados têm um impacto claro nos casos observados.</p>
</section>
<section id="análise-dos-resíduos-do-modelo-binomial-negativo" class="level3">
<h3 class="anchored" data-anchor-id="análise-dos-resíduos-do-modelo-binomial-negativo">Análise dos Resíduos do Modelo Binomial Negativo</h3>
<section id="acf-autocorrelação-e-pacf-autocorrelação-parcial-1" class="level4">
<h4 class="anchored" data-anchor-id="acf-autocorrelação-e-pacf-autocorrelação-parcial-1">ACF (Autocorrelação) e PACF (Autocorrelação Parcial)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glm_nb<span class="sc">$</span>residuals)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glm_nb<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/acf_nb-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A ACF e PACF do modelo binomial negativo também revelam autocorrelação no lag 1, sugerindo que ajustes podem ser necessários.</p>
</section>
<section id="diagnóstico-dos-resíduos-1" class="level4">
<h4 class="anchored" data-anchor-id="diagnóstico-dos-resíduos-1">Diagnóstico dos Resíduos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glm_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/diag_nb-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><strong>Resíduos vs Ajustados (Residuals vs Fitted)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Como no modelo de Poisson, verificar a aleatoriedade dos resíduos em relação aos valores ajustados.</li>
<li>Interpretação: Espera-se que os resíduos não apresentem padrões.</li>
<li>Observação: O gráfico apresenta padrões claros, sugerindo que o modelo binomial negativo não é necessariamente mais adequado do que o modelo de Poisson. A presença de padrões nos resíduos pode indicar que existem variáveis não capturadas pelo modelo ou uma estrutura não adequada para os dados.</li>
</ul>
<ol start="2" type="1">
<li><strong>Gráfico Q-Q (Q-Q Plot)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Avaliar a normalidade dos resíduos.</li>
<li>Interpretação: Espera-se que os resíduos sigam a linha reta ao longo da diagonal.</li>
<li>Observação: Não houve melhoria significativa na distribuição dos resíduos em relação ao modelo de Poisson. Isso indica que a suposição de normalidade dos resíduos não é atendida, o que pode sugerir que os dados têm uma distribuição mais complexa do que o modelo pode capturar.</li>
</ul>
<ol start="3" type="1">
<li><strong>Escala-Localização (Scale-Location)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Verificar a homogeneidade da variância.</li>
<li>Interpretação: A linha deve ser horizontal, indicando variância constante.</li>
<li>Observação: A linha é mais horizontal em comparação com o modelo de Poisson, o que sugere uma leve melhoria na homogeneidade da variância. Apesar disso, a presença de algum padrão ainda pode indicar que a variância não é completamente constante.</li>
</ul>
<ol start="4" type="1">
<li><strong>Resíduos vs Alavancagem (Residuals vs Leverage)</strong>:</li>
</ol>
<ul>
<li>Objetivo: Identificar pontos influentes.</li>
<li>Interpretação: Analisar se houve redução na quantidade de pontos influentes em relação ao modelo de Poisson.</li>
<li>Observação: Os pontos influentes 113 e 35 ainda estão presentes. Isso é uma preocupação, pois esses pontos podem estar exercendo uma influência desproporcional no modelo. É importante investigar as causas desses pontos para entender seu impacto na análise.</li>
</ul>
</section>
<section id="teste-de-overdispersion" class="level4">
<h4 class="anchored" data-anchor-id="teste-de-overdispersion">Teste de Overdispersion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_overdispersion</span>(glm_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Overdispersion test

 dispersion ratio = 1.174
          p-value =  0.36</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>No overdispersion detected.</code></pre>
</div>
</div>
<p>A razão de dispersão próxima de 1 indica que a sobre-dispersão não é um problema significativo neste modelo, e o p-valor sugere que não há evidências suficientes para rejeitar a hipótese nula de que não há sobre-dispersão. Isso sugere que o modelo binomial negativo é adequado em relação a esse aspecto.</p>
</section>
<section id="teste-de-zero-inflation" class="level4">
<h4 class="anchored" data-anchor-id="teste-de-zero-inflation">Teste de Zero Inflation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_zeroinflation</span>(glm_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for zero-inflation

   Observed zeros: 64
  Predicted zeros: 68
            Ratio: 1.07</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Model seems ok, ratio of observed and predicted zeros is within the
  tolerance range (p = 0.552).</code></pre>
</div>
</div>
<p>A razão de zeros observados para previstos está dentro da faixa de tolerância (p = 0.552). Isso indica que o modelo parece adequado em capturar a inflação de zeros presente nos dados. A proporção de zeros não é significativamente diferente, sugerindo que o modelo está lidando bem com essa característica dos dados.</p>
</section>
</section>
<section id="conclusão-do-modelo-glm-binomial-negativo" class="level3">
<h3 class="anchored" data-anchor-id="conclusão-do-modelo-glm-binomial-negativo">Conclusão do Modelo GLM Binomial Negativo</h3>
<p>A análise detalhada dos resíduos do modelo binomial negativo revelou algumas áreas de preocupação, como padrões nos resíduos e a presença de pontos influentes. Embora o modelo apresente uma leve melhoria em relação à homogeneidade da variância em comparação com o modelo de Poisson, não houve melhora significativa na normalidade dos resíduos. Os testes de sobre-dispersão e inflação de zeros sugerem que o modelo é aceitável em relação a esses aspectos, mas a presença de padrões nos resíduos e pontos influentes indica que o modelo pode não estar capturando completamente a estrutura dos dados.</p>
<hr>
</section>
</section>
<section id="ajuste-do-modelo-glarma-poisson" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-do-modelo-glarma-poisson">Ajuste do Modelo GLARMA Poisson</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>glarma_poi <span class="ot">&lt;-</span> <span class="fu">glarma</span>(y, X, <span class="at">thetaLags =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">phiLags =</span> <span class="dv">5</span>, <span class="at">type =</span> <span class="st">"Poi"</span>,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">method =</span> <span class="st">"FS"</span>, <span class="at">residuals=</span> <span class="st">"Pearson"</span>,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">maxit =</span> <span class="dv">100</span>, <span class="at">grad =</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dos modelos testados, esse apresentou o AIC mais baixo (536.2883), o que sugere que ele tem um melhor equilíbrio entre ajuste e complexidade em comparação com outros modelos.</p>
<section id="summary-do-modelo-2" class="level3">
<h3 class="anchored" data-anchor-id="summary-do-modelo-2">Summary do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glarma_poi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: glarma(y = y, X = X, type = "Poi", method = "FS", residuals = "Pearson", 
    phiLags = 5, thetaLags = c(1, 2), maxit = 100, grad = 1e-06)

Pearson Residuals:
    Min       1Q   Median       3Q      Max  
-2.0456  -0.9401  -0.1482   0.7805   4.4827  

GLARMA Coefficients:
        Estimate Std.Error z-ratio Pr(&gt;|z|)    
phi_5    0.10133   0.04734   2.141   0.0323 *  
theta_1  0.21544   0.04753   4.532 5.83e-06 ***
theta_2  0.11627   0.04895   2.375   0.0175 *  

Linear Model Coefficients:
              Estimate Std.Error z-ratio Pr(&gt;|z|)    
Intcpt          0.1314    0.1150   1.143 0.253199    
Trend          -3.9060    2.2095  -1.768 0.077090 .  
CosAnnual      -0.1003    0.1126  -0.891 0.373115    
SinAnnual      -0.5221    0.1323  -3.947  7.9e-05 ***
CosSemiAnnual   0.2059    0.1141   1.805 0.071146 .  
SinSemiAnnual  -0.3944    0.1185  -3.328 0.000874 ***

    Null deviance: 343.00  on 167  degrees of freedom
Residual deviance: 249.16  on 159  degrees of freedom
AIC: 536.2883 

Number of Fisher Scoring iterations: 20

LRT and Wald Test:
Alternative hypothesis: model is a GLARMA process
Null hypothesis: model is a GLM with the same regression structure
          Statistic  p-value    
LR Test       27.61 4.39e-06 ***
Wald Test     34.85 1.31e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Em geral, o modelo GLARMA ajusta-se bem aos dados, capturando a dependência temporal e apresentando coeficientes significativos para várias variáveis.</p>
</section>
<section id="análise-dos-resíduos-do-modelo-1" class="level3">
<h3 class="anchored" data-anchor-id="análise-dos-resíduos-do-modelo-1">Análise dos Resíduos do Modelo</h3>
<section id="acf-autocorrelação-e-pacf-autocorrelação-parcial-2" class="level4">
<h4 class="anchored" data-anchor-id="acf-autocorrelação-e-pacf-autocorrelação-parcial-2">ACF (Autocorrelação) e PACF (Autocorrelação Parcial)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glarma_poi<span class="sc">$</span>residuals)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glarma_poi<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/glarma_acf_poi-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A ACF e PACF do modelo poisson não revelam autocorrelações significativas, o que indica o modelo captura bem a dependencia temporal.</p>
</section>
<section id="diagnóstico-dos-resíduos-2" class="level4">
<h4 class="anchored" data-anchor-id="diagnóstico-dos-resíduos-2">Diagnóstico dos Resíduos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glarma_poi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/glarma_diag_poisson-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p><strong>Observed vs Fixed vs GLARMA:</strong> Esse gráfico compara os dados observados (linha preta) com os ajustes do modelo fixo (linha azul) e do GLARMA (linha vermelha). A linha do GLARMA acompanha bem a dos dados obserados, porém os ajustes do modelo fixo não segue tão bem.</p></li>
<li><p><strong>Pearson Residuals:</strong> Resíduos de Pearson são as diferenças entre os valores observados e o valores esperados, ajustando-se pelas variações esperadas. O gráfico mostra resíduos sem padrões claros ou desvios maiores, o que sugere um modelo possivelmente adequado.</p></li>
<li><p><strong>Histogram of Uniform PIT:</strong> Esse histograma deve ser aproximadamente uniforme para indicar um bom ajuste. Há um desvio em relação à linha de referência, o que indica que o modelo não está adequadamente ajustado.</p></li>
<li><p><strong>Histogram of Randomized Residuals:</strong> Aqui, espera-se uma distribuição simétrica em torno de zero e com formato próximo ao normal. O gráfico apresenta assimetria e não se aproxima de uma distribuição normal, sugerindo que o modelo não está ajustado corretamente.</p></li>
<li><p><strong>Q-Q Plot of Randomized Residuals:</strong> O gráfico quantil-quantil deve exibir pontos alinhados à linha pontilhada para indicar normalidade nos resíduos. Os pontos se apresentam relativamente proximos a linha porém há desvios nas extremidades.</p></li>
<li><p><strong>ACF of Randomized Residuals:</strong> A ausência de autocorrelações significativas (barras fora da área pontilhada) indica que o modelo capturou bem a dependência temporal, reforçando a qualidade do ajuste.</p></li>
</ol>
</section>
</section>
</section>
<section id="conclusão-do-modelo-glarma-poisson" class="level2">
<h2 class="anchored" data-anchor-id="conclusão-do-modelo-glarma-poisson">Conclusão do Modelo GLARMA Poisson</h2>
<p>O modelo GLARMA Poisson capturou bem a dependência temporal dos dados, apresentando coeficientes significativos e o menor AIC entre os modelos testados. Embora a análise dos resíduos indique um ajuste geral adequado, alguns gráficos sugerem falhas na adequação da distribuição dos resíduos. No entanto, o modelo ainda oferece um bom equilíbrio entre ajuste e complexidade, sendo uma escolha sólida para a série analisada.</p>
</section>
<section id="ajuste-do-modelo-glarma-binomial-negativo" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-do-modelo-glarma-binomial-negativo">Ajuste do Modelo GLARMA Binomial Negativo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>glarma_nb <span class="ot">&lt;-</span> <span class="fu">glarma</span>(y, X, <span class="at">thetaLags =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">phiLags =</span> <span class="dv">4</span>, <span class="at">type =</span> <span class="st">"NegBin"</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">method =</span> <span class="st">"FS"</span>, <span class="at">residuals=</span> <span class="st">"Pearson"</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">maxit =</span> <span class="dv">100</span>, <span class="at">grad =</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esse modelo foi o que apresentou menor AIC (514.1978), em comparação a outros modelos testados.</p>
<section id="summary-do-modelo-3" class="level3">
<h3 class="anchored" data-anchor-id="summary-do-modelo-3">Summary do Modelo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: glarma(y = y, X = X, type = "NegBin", method = "FS", residuals = "Pearson", 
    phiLags = 4, thetaLags = c(1, 2), maxit = 100, grad = 1e-06)

Pearson Residuals:
    Min       1Q   Median       3Q      Max  
-1.2262  -0.7451  -0.0504   0.7807   3.8074  

Negative Binomial Parameter:
      Estimate Std.Error z-ratio Pr(&gt;|z|)
alpha    1.594     1.068   1.492    0.136

GLARMA Coefficients:
        Estimate Std.Error z-ratio Pr(&gt;|z|)    
phi_4    0.16837   0.07528   2.237  0.02531 *  
theta_1  0.28172   0.06599   4.269 1.96e-05 ***
theta_2  0.26796   0.08523   3.144  0.00167 ** 

Linear Model Coefficients:
              Estimate Std.Error z-ratio Pr(&gt;|z|)   
Intcpt          0.1805    0.1738   1.038  0.29913   
Trend          -3.3590    3.3081  -1.015  0.30992   
CosAnnual      -0.1145    0.1678  -0.682  0.49502   
SinAnnual      -0.6011    0.1895  -3.172  0.00152 **
CosSemiAnnual   0.3341    0.1430   2.336  0.01951 * 
SinSemiAnnual  -0.3837    0.1349  -2.845  0.00444 **

    Null deviance: 201.22  on 167  degrees of freedom
Residual deviance: 190.84  on 158  degrees of freedom
AIC: 515.9526 

Number of Fisher Scoring iterations: 100

LRT and Wald Test:
Alternative hypothesis: model is a GLARMA process
Null hypothesis: model is a GLM with the same regression structure
          Statistic  p-value    
LR Test       11.70  0.00847 ** 
Wald Test     27.21 5.33e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="análise-dos-resíduos-do-modelo-2" class="level3">
<h3 class="anchored" data-anchor-id="análise-dos-resíduos-do-modelo-2">Análise dos Resíduos do Modelo</h3>
<section id="acf-autocorrelação-e-pacf-autocorrelação-parcial-3" class="level4">
<h4 class="anchored" data-anchor-id="acf-autocorrelação-e-pacf-autocorrelação-parcial-3">ACF (Autocorrelação) e PACF (Autocorrelação Parcial)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(glarma_nb<span class="sc">$</span>residuals)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(glarma_nb<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/glarma_acf_nb-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A ACF e PACF do modelo binomial negativo não revelam autocorrelações significativas, o que indica o modelo captura bem a dependencia temporal.</p>
</section>
<section id="diagnóstico-dos-resíduos-3" class="level4">
<h4 class="anchored" data-anchor-id="diagnóstico-dos-resíduos-3">Diagnóstico dos Resíduos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glarma_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorio1_files/figure-html/glarma_diag_nb-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p><strong>Observed vs Fixed vs GLARMA:</strong> Assim como no modelo poisson, a linha vermelha está mais proxima da preta do que a linha azul.</p></li>
<li><p><strong>Pearson Residuals:</strong> Os resíduos mostram-se sem padrões claros ou desvios maiores, assim como no modelo anterior.</p></li>
<li><p><strong>Histogram of Uniform PIT:</strong> O desvio da uniformidade ainda persiste, sugerindo imprecisão no modelo.</p></li>
<li><p><strong>Histogram of Randomized Residuals:</strong> Diferentimente do modelo poisson, a distribuição dos resíduos se aproxima da normal, com menor assimetria.</p></li>
<li><p><strong>Q-Q Plot of Randomized Residuals:</strong> Os pontos no gráfico seguem a linha pontilhada, porém como no modelo poisson, há desvios nas extremidades.</p></li>
<li><p><strong>ACF of Randomized Residuals:</strong> A ausência de autocorrelações reforça o bom ajuste.</p></li>
</ol>
</section>
</section>
<section id="conclusão-do-modelo-glarma-binomial-negativo" class="level3">
<h3 class="anchored" data-anchor-id="conclusão-do-modelo-glarma-binomial-negativo">Conclusão do Modelo GLARMA Binomial Negativo</h3>
<p>O GLARMA Binomial Negativo apresenta um ajuste melhor que o Poisson, conforme o AIC mais baixo, com resíduos mais próximos da normalidade e melhor captura da dependência temporal.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>